services:
  web-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./index.html:/usr/src/app/index.html
          
  backend:
    build: backend
    ports:
      - "3000:3000"
      